package com.jesper.mvc.controller;

public enum Actions {
	VIEW_ALL_MEMBERS,
	VIEW_ALL_MEMBERS_VERBOSE,
	CREATE_MEMBER,
	UPDATE_MEMBER,
	DELETE_MEMBER,
	VIEW_MEMBER,
	CREATE_BOAT,
	UPDATE_BOAT,
	DELETE_BOAT,
	VIEW_BOAT,
	QUIT,
	NOACTION
}
